### ISSUE TITLE
Behaviors are processed twice when a filter is used in a subquery

### ISSUE THREAD

**Issue by lippserd** [Icinga/ipl-orm#48]
If the filter processor decides to move a filter to a subquery, the behaviors are re-evaluated. Even though the subquery is filtered with already processed values.

**Comment by lippserd** [comment]
Have a look at the referenced commits please. A behavior must not run twice on the same value.

**Comment by nilmerg** [comment]
I have, and it shows a behavior that rewrites a condition. It's the behavior's responsibility to handle that, like you've done in the commit.

**Comment by lippserd** [comment]
> I have, and it shows a behavior that rewrites a condition. It's the behavior's responsibility to handle that, like you've done in the commit.

No, this has to be fixed. The `Binary` behavior already looks like crap because of that and now we have the same in the referenced `IP` behavior.
