### ISSUE TITLE
Allow to pick off specific columns from query

### ISSUE THREAD

**Issue by yhabteab** [Icinga/ipl-orm#96]
We should provide a way to only pluck particular columns from the query. I.e. instead of having the user do all the query traversal, one can simply hand over a method with the desired columns and the query takes care of all the work. A suggestion from Eric on method naming, this would be called `pluck(string ...$columns)`.

```php
// This would be replaced by...
foreach ($lastFingerprints as $lastFingerprint) {
      $lastFingerprintsArr[] = $lastFingerprint->fingerprint;
}

// ... the following:
$lastFingerprintsArr = $lastFingerprints->pluck('fingerprint');
```

**Comment by nilmerg** [comment]
Resolved by #99
